---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: AllowedRegistry
metadata:
  name: machine-learning
spec:
  enforcementAction: {{ .Values.enforcementAction }}
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
      - apiGroups: ["apps"]
        kinds: ["Deployment"]
    excludedNamespaces:
      - "argocd"
      - "kube-system"
      - "gatekeeper"
  parameters:
    repos:
      - "openpolicyagent/opa"
      # - "jupyter/tensorflow-notebook"
