---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatekeeper-policies
  namespace: argocd
spec:
  project: core-components
  source:
    repoURL: https://github.com/dnascimento/eks-apps.git
    targetRevision: HEAD
    path: policies/gatekeeper-policies
    helm:
      valueFiles:
        - values-{{ .Values.stage }}.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: gatekeeper-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
